/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { GraduationTypeWhereUniqueInput } from "../../graduationType/base/GraduationTypeWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { InstituteWhereUniqueInput } from "../../institute/base/InstituteWhereUniqueInput";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { MArketProfileWhereUniqueInput } from "../../mArketProfile/base/MArketProfileWhereUniqueInput";
import { UserGroupListRelationFilter } from "../../userGroup/base/UserGroupListRelationFilter";
import { IntFilter } from "../../util/IntFilter";
@InputType()
class GroupWhereInput {
  @ApiProperty({
    required: false,
    type: () => GraduationTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GraduationTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => GraduationTypeWhereUniqueInput, {
    nullable: true,
  })
  graduationType?: GraduationTypeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => InstituteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => InstituteWhereUniqueInput)
  @IsOptional()
  @Field(() => InstituteWhereUniqueInput, {
    nullable: true,
  })
  institute?: InstituteWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isActive?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => MArketProfileWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MArketProfileWhereUniqueInput)
  @IsOptional()
  @Field(() => MArketProfileWhereUniqueInput, {
    nullable: true,
  })
  marketProfile?: MArketProfileWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => UserGroupListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserGroupListRelationFilter)
  @IsOptional()
  @Field(() => UserGroupListRelationFilter, {
    nullable: true,
  })
  userGroups?: UserGroupListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  year?: IntFilter;
}
export { GroupWhereInput };
