/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { GraduationTypeWhereUniqueInput } from "../../graduationType/base/GraduationTypeWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsBoolean,
  IsString,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { InstituteWhereUniqueInput } from "../../institute/base/InstituteWhereUniqueInput";
import { MArketProfileWhereUniqueInput } from "../../mArketProfile/base/MArketProfileWhereUniqueInput";
import { UserGroupUpdateManyWithoutGroupsInput } from "./UserGroupUpdateManyWithoutGroupsInput";
@InputType()
class GroupUpdateInput {
  @ApiProperty({
    required: false,
    type: () => GraduationTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GraduationTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => GraduationTypeWhereUniqueInput, {
    nullable: true,
  })
  graduationType?: GraduationTypeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => InstituteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => InstituteWhereUniqueInput)
  @IsOptional()
  @Field(() => InstituteWhereUniqueInput, {
    nullable: true,
  })
  institute?: InstituteWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => MArketProfileWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MArketProfileWhereUniqueInput)
  @IsOptional()
  @Field(() => MArketProfileWhereUniqueInput, {
    nullable: true,
  })
  marketProfile?: MArketProfileWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => UserGroupUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => UserGroupUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => UserGroupUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  userGroups?: UserGroupUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  year?: number;
}
export { GroupUpdateInput };
